# Node.js
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install @angular/cli -g
    npm install
    npm run build
  displayName: 'npm install and build'

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Free Trial (b3ba5f50-a440-46aa-aeb9-896ef73c3279)'
    appType: 'webApp'
    WebAppName: 'nitinangulardemoprod'
    deployToSlotOrASE: true
    ResourceGroupName: 'nitinjaiswal'
    SlotName: 'production'
    packageForLinux: 'dist/angularDemoApp'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'